language: ruby
rvm:
  - 2.0.0
env:
- RELEAF_DUMMY_RAILS3_DB_USERNAME=travis RELEAF_DUMMY_RAILS3_DB_PASSWORD="" RELEAF_DUMMY_RAILS3_DB_NAME=myapp
before_script: bundle exec rake dummy:setup
script: xvfb-run rspec
